In [1]:
import torch 
from torch import nn
torch.cuda.is_available()

True

In [2]:
torch.cuda.device_count()

1

In [3]:
torch.cuda.current_device()

0

In [4]:
torch.cuda.get_device_name(0)

'GeForce GTX 950M'

In [5]:
x=torch.tensor([1,2,3])
x

tensor([1, 2, 3])

In [6]:
x=x.cuda(0)
x

tensor([1, 2, 3], device='cuda:0')

In [7]:
x.device

device(type='cuda', index=0)

In [8]:
device=torch.device('cuda' if torch.cuda.is_available() else 'cpu')
x=torch.tensor([1,2,3,],device=device)
x

tensor([1, 2, 3], device='cuda:0')

In [9]:
y=x**2
y

tensor([1, 4, 9], device='cuda:0')

In [10]:
#z=y+x.cpu()

RuntimeError: expected backend CUDA and dtype Long but got backend CPU and dtype Long

In [ ]:
net = nn.Linear(3,1)
list(net.parameters())[0].device


In [ ]:
net.cuda()
list(net.parameters())[0].device

In [ ]:
x=torch.rand(2,3).cuda()
net(x)