In [1]:
import torch 
from torch import nn
from torch.nn import init
net=nn.Sequential(nn.Linear(4,3),nn.ReLU(),nn.Linear(3,1))

print(net)
X=torch.rand(2,4)
Y=net(X).sum()

Sequential(
  (0): Linear(in_features=4, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
)


In [2]:
print(type(net.named_parameters))
for name,param in net.named_parameters():
    print(name,param.size())
    

<class 'method'>
0.weight torch.Size([3, 4])
0.bias torch.Size([3])
2.weight torch.Size([1, 3])
2.bias torch.Size([1])


In [3]:
for name,param in net[0].named_parameters():
    print(name,param.size(),type(param))
    

weight torch.Size([3, 4]) <class 'torch.nn.parameter.Parameter'>
bias torch.Size([3]) <class 'torch.nn.parameter.Parameter'>


In [4]:
class MyModel(nn.Module):
    def __init__(self,**kwargs):
        super(MyModel,self).__init__(**kwargs)
        self.weight1=nn.Parameter(torch.rand(20,20))
        self.weight2=torch.rand(20,20)
        
    def forward(self,x):
        pass
    
n=MyModel()
for name,param in  n.named_parameters():
    print(name)

weight1


In [11]:
weight_0=list(net[0].parameters())[0]
print(weight_0,'****')
print(weight_0.data)
print(weight_0.grad)
#Y.backward()
print(weight_0.grad)

Parameter containing:
tensor([[ 0.3109, -0.0440,  0.4097,  0.2135],
        [-0.2724, -0.4965,  0.0353, -0.4640],
        [ 0.3451, -0.3225, -0.2494, -0.1800]], requires_grad=True) ****
tensor([[ 0.3109, -0.0440,  0.4097,  0.2135],
        [-0.2724, -0.4965,  0.0353, -0.4640],
        [ 0.3451, -0.3225, -0.2494, -0.1800]])
tensor([[0.3211, 0.1522, 0.2904, 0.2332],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])
tensor([[0.3211, 0.1522, 0.2904, 0.2332],
        [0.0000, 0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000, 0.0000]])


In [15]:
for name,param in net.named_parameters():
    if 'weight' in name:
        init.normal_(param,mean=0,std=0.01)
        print(name,param.data)

0.weight tensor([[ 0.0084, -0.0021,  0.0044,  0.0193],
        [ 0.0242, -0.0024,  0.0013, -0.0048],
        [-0.0181, -0.0104, -0.0096,  0.0071]])
2.weight tensor([[ 0.0082, -0.0152, -0.0027]])


In [20]:
for name,param in net.named_parameters():
    if 'bias' in name:
        init.constant_(param,val=0)
        print(name,param.data)
        print(name,param,'*********')

0.bias tensor([0., 0., 0.])
0.bias Parameter containing:
tensor([0., 0., 0.], requires_grad=True) *********
2.bias tensor([0.])
2.bias Parameter containing:
tensor([0.], requires_grad=True) *********


In [22]:
def init_weight_(tensor):
    with torch.no_grad():
        tensor.uniform_(-10,10)
        tensor*=(tensor.abs()>=5).float()
        
for name, param in net.named_parameters():
    if 'weight' in name:
        init_weight_(param)
        print(name,param.data)
        

0.weight tensor([[ 9.5404,  7.4537,  0.0000,  8.3451],
        [-0.0000, -0.0000,  6.4133, -7.8836],
        [ 0.0000,  0.0000,  7.7465,  0.0000]])
2.weight tensor([[0., 0., 0.]])


In [24]:
for name,param in net.named_parameters():
    if 'bias' in name:
        param.data+=1
        print(name,param.data)

0.bias tensor([2., 2., 2.])
2.bias tensor([2.])


In [28]:
linear=nn.Linear(1,1,bias=False)
net=nn.Sequential(linear,linear)
print(net)
for name,param in net.named_parameters():
    init.constant_(param,val=3)
    print(name,param.data)
    

Sequential(
  (0): Linear(in_features=1, out_features=1, bias=False)
  (1): Linear(in_features=1, out_features=1, bias=False)
)
0.weight tensor([[3.]])


In [29]:
print(id(net[0])==id(net[1]))
print(id(net[0].weight)==id(net[1].weight))

True
True


In [30]:
x=torch.ones(1,1)
y=net(x).sum()
print(y)
y.backward()
print(net[0].weight.grad)

tensor(9., grad_fn=<SumBackward0>)
tensor([[6.]])
