In [3]:
import torch 
from torch import nn
x=torch.ones(3)
torch.save(x,'x.pt')
x2=torch.load('x.pt')
x2

tensor([1., 1., 1.])

In [4]:
y=torch.zeros(4)
torch.save([x,y],'xy.pt')
xy_list=torch.load('xy.pt')
xy_list

[tensor([1., 1., 1.]), tensor([0., 0., 0., 0.])]

In [5]:
torch.save({'x':x,'y':y},'xy_dict.pt')
xy=torch.load('xy_dict.pt')
xy

{'x': tensor([1., 1., 1.]), 'y': tensor([0., 0., 0., 0.])}

In [6]:
class MLP(nn.Module):
    def __init__(self):
        super(MLP,self).__init__()
        self.hidden=nn.Linear(3,2)
        self.act=nn.ReLU()
        self.output=nn.Linear(2,1)
    def forward(self,x):
        a=self.act(self.hidden(x))
        return self.output(a)
    
net=MLP()
net.state_dict()

OrderedDict([('hidden.weight',
              tensor([[ 0.2032,  0.1124,  0.0632],
                      [ 0.0570,  0.3502, -0.3113]])),
             ('hidden.bias', tensor([0.2300, 0.1180])),
             ('output.weight', tensor([[-0.0319,  0.4067]])),
             ('output.bias', tensor([0.0690]))])

In [7]:
optimizer=torch.optim.SGD(net.parameters(),lr=0.001,momentum=0.9)
optimizer.state_dict()

{'state': {},
 'param_groups': [{'lr': 0.001,
   'momentum': 0.9,
   'dampening': 0,
   'weight_decay': 0,
   'nesterov': False,
   'params': [2570740157320, 2570740157400, 2570690751688, 2570740157240]}]}

In [9]:
X=torch.randn(2,3)
Y=net(X)
print(Y,'11111111111')
PATH="./net.pt"
torch.save(net.state_dict(),PATH)

net2=MLP()
net2.load_state_dict(torch.load(PATH))
Y2=net2(X)
print(Y2,'22222222222')
print(Y2==Y)

tensor([[0.0540],
        [0.0681]], grad_fn=<AddmmBackward>) 11111111111
tensor([[0.0540],
        [0.0681]], grad_fn=<AddmmBackward>) 22222222222
tensor([[1],
        [1]], dtype=torch.uint8)
