In [7]:
import torch
import numpy as np
num_inputs=2
num_examples=1000
true_w=[2,-3.4]
true_b=4.2
features=torch.tensor(np.random.normal(0,1,(num_examples,num_inputs)),dtype=torch.float)
labels=true_w[0]*features[:,0]+true_w[1]*features[:,1]+true_b
labels+=torch.tensor(np.random.normal(0,0.01,size=labels.size()),dtype=torch.float)
# print(true_w[0])
# print(features[0,0])

In [8]:
import torch.utils.data as Data
batch_size=10
dataset=Data.TensorDataset(features,labels)
data_iter=Data.DataLoader(dataset,batch_size,shuffle=True)
for X,y in data_iter:
    print(X,y)
    break

tensor([[ 0.9452,  0.0949],
        [ 0.3324,  1.5020],
        [-0.2324, -0.8312],
        [-0.4432,  0.9312],
        [ 0.1907,  0.5686],
        [ 0.3099,  0.4859],
        [ 0.5435,  0.7375],
        [-1.1281, -0.2938],
        [-0.7038, -2.5343],
        [-0.0147, -0.8714]]) tensor([ 5.7622, -0.2367,  6.5633,  0.1416,  2.6594,  3.1824,  2.7729,  2.9356,
        11.4207,  7.1193])


In [11]:
from torch import nn
class LinearNet(nn.Module):
    def __init__(self,n_feature):
        super(LinearNet,self).__init__()
        self.linear=nn.Linear(n_feature,1)
        
    def forward(self,x):
        y=self.linear(x)
        return y
        
net=LinearNet(num_inputs)
print(net)

LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [12]:
net = nn.Sequential(
nn.Linear(num_inputs,1)
)
print(net)
print(net[0])

Sequential(
  (0): Linear(in_features=2, out_features=1, bias=True)
)
Linear(in_features=2, out_features=1, bias=True)


In [13]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[-0.4859,  0.4652]], requires_grad=True)
Parameter containing:
tensor([-0.0615], requires_grad=True)


In [14]:
from torch.nn import init
init.normal_(net[0].weight,mean=0,std=0.01)
init.constant_(net[0].bias,val=0)

Parameter containing:
tensor([0.], requires_grad=True)

In [15]:
loss=nn.MSELoss()

In [17]:
import torch.optim as optim
optimizer=optim.SGD(net.parameters(),lr=0.03)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [21]:
# optimizer=optim.SGD([{'params':net.subnet1.parameters()},
#                      {'params':net.subnet2.parameters(),'lr':0.01}
#                     ],lr=0.03)


In [20]:
for param_group in optimizer.param_groups:
    param_group['lr']*=0.1

In [24]:
num_epochs=10
for epoch in range(1,num_epochs+1):
    for X,y in data_iter:
        output=net(X)
        l=loss(output,y.view(-1,1))
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
    print('epoch %d,loss:%f'%(epoch,l.item()))

epoch 1,loss:0.173133
epoch 2,loss:0.123035
epoch 3,loss:0.019890
epoch 4,loss:0.006041
epoch 5,loss:0.001338


In [25]:
dense=net[0]
print(true_w,dense.weight)
print(true_b,dense.bias)

[2, -3.4] Parameter containing:
tensor([[ 1.9914, -3.3763]], requires_grad=True)
4.2 Parameter containing:
tensor([4.1643], requires_grad=True)
